#!/usr/bin/env bash
set -euo pipefail

# Run from the repository root; upstream checkouts are provided by the workflow.
upstream_root="${1:?Usage: scripts/sync-skills.sh UPSTREAM_CHECKOUT_DIRECTORY}"
for mapping in clean-coding:clean-development clean-code-review:clean-code-review; do
  repo="${mapping%%:*}"
  skill="${mapping#*:}"
  source_dir="$upstream_root/$repo/skills/$skill"
  test -f "$source_dir/SKILL.md"
  git -C "$upstream_root/$repo" rev-parse HEAD > /dev/null
  # Validate both sources before modifying either downstream copy.
done
for mapping in clean-coding:clean-development clean-code-review:clean-code-review; do
  repo="${mapping%%:*}"
  skill="${mapping#*:}"
  mkdir -p "skills/$skill"
  rsync -a --delete "$upstream_root/$repo/skills/$skill/" "skills/$skill/"
done
{
  echo '# Upstream skill revisions'
  echo
  echo 'Generated by `scripts/sync-skills.sh`. Edit skills in their canonical repositories.'
  echo
  for mapping in clean-coding:clean-development clean-code-review:clean-code-review; do
    repo="${mapping%%:*}"
    skill="${mapping#*:}"
    revision="$(git -C "$upstream_root/$repo" rev-parse HEAD)"
    echo "- $skill: https://github.com/wgtechlabs/$repo/tree/$revision/skills/$skill"
  done
} > skills/UPSTREAM.md
